### ISSUE TITLE
Please version prometheus libs too

### ISSUE THREAD

**Issue by nim-nim** [prometheus/common#103]
It would be mightily fine if common prometheus packages were reved like prometheus and its exporters, instead of having golden prometheus versions depend on magic vendor snapshots

That would help integrate prometheus in linux distributions

**Comment by SamWhited** [comment]
Gentle ping. Even tagging a pre-release version (v0.0.1 or similar) that could be used by Prometheus would make our transitive dependencies much easier to keep track of when people have to look at the file. Thanks for your time and consideration.

**Comment by beorn7** [comment]
In particular with the expectation that Go modules will be what dependency management in Go finally settles on, a version tag makes a lot of sense.

**Comment by simonpasquier** [comment]
Agreed that it makes a lot of sense now that we have all our projects using Go modules.

**Comment by brian-brazil** [comment]
As this is also an internal library, I think following tsdb and just having tags is the way to go here.

**Comment by brian-brazil** [comment]
There's now a v0.1.0 tag.

**Comment by nim-nim** [comment]
Thanks a lot!
