### ISSUE TITLE
Unable to print logs to a file

### ISSUE THREAD

**Issue by amankapoor** [prometheus/common#104]
Hey, I am unable to print logs to a file.

`f, err := os.OpenFile("logs.log", os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0666)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()
	log.NewLogger(f)
	log.Info("Sucesssss")`

This is going to console and I think my issue is related with #82 . What is happening and how can this be fixed?

**Comment by amankapoor** [comment]
I would like to add that after opening this issue, I tried with the original logrus package to achieve the same.

````
package main

import (
	"os"

	log "github.com/sirupsen/logrus"
)

func main() {
	f, err := os.OpenFile("ak.log", os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0666)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	log.New()
	//l.Out = f
	log.SetOutput(f)

	log.Info("Success?")
}
````

if you use `l.out = f`, then it won't write to file. I have no idea why, but this is how common/log is working as of now, you can refer to line 257 of common/log/log.go file. If you go deeper in the SetOutput function, then you will find that it sets locks.

Using log.SetOutput prints in the file. I am trying to solve it now.

**Comment by amankapoor** [comment]
Hi, so I just came back home and I have solved it. Here is the link to the solution https://github.com/amankapoor/prometheus-common-log-to-file/. Do you want to accept it as a PR, or if we can improve it? Let me know.

**Comment by brian-brazil** [comment]
This relates to the old log library (we use promlog now), which is deprecated and no longer in use.
