### ISSUE TITLE
expfmt: Consider filter the illegal metrics rather than drop all the metrics

### ISSUE THREAD

**Issue by i19** [prometheus/common#105]
https://github.com/prometheus/common/blob/2f17f4a9d485bf34b4bfaccc273805040e4f86c8/expfmt/decode.go#L104-L108

Rather than return error cause losing the whole metrics, it would be reasonable to just filter them and log it.

**Comment by brian-brazil** [comment]
Invalid output should cause the entire scrape to fail, as partial scrapes are very difficult to deal with. I'd suggest filing a bug with the client library you're using to fix their output.

**Comment by i19** [comment]
The strange thing is, the error  occur  when i federate from another prometheus.  i can see the illegal metric at the prometheus which was being federated.  lol

**Comment by brian-brazil** [comment]
Previous versions didn't validate as much as they should have. If you upgrade your Prometheus it should handle this correctly.

**Comment by i19** [comment]
Thanks
I'm using 1.6.1
I will upgrade it as soon as possible
