### ISSUE TITLE
model.ParseDuration bug

### ISSUE THREAD

**Issue by AlekSi** [prometheus/common#117]
`"1m0s"` can be parsed normally by `time.ParseDuration` (https://play.golang.org/p/QbEuk34UKSm) but not by `model.ParseDuration`:
```
not a valid duration string: "1m0s"
```

**Comment by fabxc** [comment]
That's intended behavior. We do support days, weeks, and years (which stdlib `time` does not) but only support a single unit argument. This is not likely to change.

**Comment by AlekSi** [comment]
That issue comes from a code working with Prometheus configuration file parsing and rendering, but not a part of Prometheus itself. We pass `string`s across API boundaries, not `time.Duration`, and both client (which uses `time.Duration` internally) and server (which uses `model.Duration`) should play nicely with each other. Will you accept a change if it is strictly backward-compatible with current implementation?

**Comment by brian-brazil** [comment]
I believe we're all consistent in this these days, and as Fabian says it's not planned to extend this syntax.
