### ISSUE TITLE
expfmt.Decoder rejects an endpoint Prometheus TSD successfully scrapes

### ISSUE THREAD

**Issue by vjsamuel** [prometheus/common#118]
Commit used:
prometheus/common: HEAD
prometheus/prometheus: HEAD

The common module of prometheus is used by elastic/beats https://github.com/elastic/beats/blob/master/metricbeat/helper/prometheus.go#L27 to do scraping of prometheus end points. The following endpoint which comes from envoyproxy https://github.com/envoyproxy/envoy/blob/master/source/server/http/admin.cc :
https://gist.githubusercontent.com/vjsamuel/5898d02f8039d8d1bae4d8642182d1c3/raw/deff0c16f746bb2ab7a959c4d5ed9856d17c425d/gistfile1.txt

is successfully scraped by the prometheus TSD and fails to be decoded by the Decoder with error:
```
text format parsing error in line 9: second TYPE line for metric name "envoy_listener_http_downstream_rq_xx", or TYPE reported after samples
```

Can there be consistency in the common module with the scraper module in prometheus TSD?

**Comment by brian-brazil** [comment]
The parser in Prometheus 2.0 is less strict for the sake of efficiency, this is still bad output though and should be fixed by Envoy.

**Comment by vjsamuel** [comment]
@brian-brazil would it be possible to establish the same parsing rules on `expfmt` as well?

**Comment by brian-brazil** [comment]
No, that'd mean we have no proper parser.

**Comment by brian-brazil** [comment]
There's nothing for us to do here, we'll have a fast parser and a correct parser for the foreseeable future.
