### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by TheTincho** [prometheus/common#12]
Hi,

A new dependency, a new Debian package! :-)

There is a small problem with this one: even if most files have a copyright and license statement, not all of them have, and you don't have an explicit one at the root.of the project either. In particular, these source files have no attribution: 

> route/route_test.go
> route/route.go

And same thing with the test data.

Thanks!

**Comment by juliusv** [comment]
@TheTincho Thanks for noticing this! Fix out in https://github.com/prometheus/common/pull/13.
