### ISSUE TITLE
Feature: HTTP Config Additional Headers

### ISSUE THREAD

**Issue by therealgambo** [prometheus/common#140]
As slightly touched on in https://github.com/prometheus/prometheus/issues/4314 having the ability to provide custom headers for webhooks would solve any bespoke integration with 3rd party API's that do not conform to strict authorization formats.

**Comment by brian-brazil** [comment]
The alertmanager webhook is intended to be used by something specifically designed to accept a webhook, not to be able to talk to arbitrary http-based protocols. If you need this you should write a webhook receiver that speaks the protocol that you need.

This code is also used in several other places, allowing headers to be added would be problematic for them.

**Comment by therealgambo** [comment]
> We're not actively adding new receivers, we recommend implementing custom notification integrations via the webhook receiver.

Boldly noted in the documentation, or is this no longer the case? I'm not going to put in the work for it to be blindly disregarded.

Also, if that is the case, can we re-open https://github.com/prometheus/alertmanager/pull/444 for review and merge?

**Comment by brian-brazil** [comment]
That's still the case.

I don't see how that makes a difference for that PR. The reasons for rejecting it remain valid.

**Comment by simonpasquier** [comment]
Closing it as the original issue was because OpsGenie didn't support standard HTTP authorization headers. This is no longer true, see https://github.com/prometheus/alertmanager/pull/444#issuecomment-424685490.
