### ISSUE TITLE
NewClientFromConfig has no mechanism to set timeouts

### ISSUE THREAD

**Issue by jacksontj** [prometheus/common#144]
`NewClientFromConfig` calls `NewRoundTripperFromConfig` which returns an `http.RoundTripper`. That interface has no mechanism to set dial options (like dial timeout, etc.). Under the hood the `DialContext` is set to one from `go-conntrack` -- which supports passing a [dialer](https://github.com/mwitkow/go-conntrack#conntrack-dialer-for-http-defaultclient). I'd like a mechanism to pass these dial options in. The main reason being that as it stands today if the scrape target etc. is blocking the packets or slow the scrape hands for quite a while (holding FDs, etc.).

I see a couple options:
- we add some options to the `HTTPClientConfig` for this
- we add a new method `NewClientFromConfigWithDialer` which takes a dialer and does the "right thing"
- something else I haven't thought of yet

**Comment by brian-brazil** [comment]
You can set a context on the request, that's how the blackbox exporter does it for example.

**Comment by jacksontj** [comment]
This let's me set a timeout for the entire request. I'm looking to
specifically set a dial timeout. As an example. I want to timeout if tcp
doesn't open in 100ms, but I'm okay with waiting 1s for the entire request.
The only way to get that behavior is to set a dial timeout.

**Comment by brian-brazil** [comment]
This code is for use by the Prometheus project, what's the use case for that within that context?

**Comment by jacksontj** [comment]
As described in the initial issue. I'd like to not wait for the entire
timeout (5s let's say) if I can't connect quickly. This reduces the number
of fds that are held open etc. for hosts that are in SD but aren't actually
available for whatever reason.

On Sep 21, 2018 7:41 AM, "Brian Brazil" <notifications@github.com> wrote:

This code is for use by the Prometheus project, what's the use case for
that within that context?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/prometheus/common/issues/144#issuecomment-423556014>,
or mute the thread

**Comment by brian-brazil** [comment]
It doesn't appear that Prometheus needs this, and there's already a way to do it, so closing.

**Comment by jacksontj** [comment]
To be clear, there is **not** a way to do what I was describing (set dial timeouts) -- but it seems that no one else is interested
