### ISSUE TITLE
Support JSON formatting of logs

### ISSUE THREAD

**Issue by carlpett** [prometheus/common#145]
`common/log` supports a json formatter for the log output, which `common/promlog` does not. Would a PR to add a flag for switching between json/plain text be acceptable? This would make it much easier to integrate exporters etc into environments which mandate structured logging (vs having an extra binary to rewrite the logs).
go-kit already has the necessary `NewJSONLogger` function, which could be conditionally used instead of `NewLogfmtLogger` into here:
https://github.com/prometheus/common/blob/c7de2306084e37d54b8be01f3541a8464345e9a5/promlog/log.go#L58-L63

**Comment by brian-brazil** [comment]
See #136

**Comment by simonpasquier** [comment]
Closing as #136 is now merged.
