### ISSUE TITLE
Optimize `MetricFamilyToText`

### ISSUE THREAD

**Issue by beorn7** [prometheus/common#146]
This [code](https://github.com/prometheus/common/blob/master/expfmt/text_create.go) has been written with the assumption it would never be a in a hot code path. With Prometheus 2.x dropping protobuf support, scrapes by Prometheus are now always using the text format, and thus every monitored Go program is currently running this code quite a lot. (@mxinden has just told me how the kube-state-metrics CPU profiling is dominated by [`labelPairsToText`](https://github.com/prometheus/common/blob/master/expfmt/text_create.go#L243).)

client_golang will undergo more invasive changes in the future, which will provide opportunities to solve the problem in another way, but `MetricFamilyToText` has a lot of low hanging fruit to make the current usage of client_golang more efficient.

**Comment by mxinden** [comment]
Thanks a bunch for tracking this here @beorn7!

Can you elaborate a bit further on the low-hanging fruits? Maybe I can help.

**Comment by beorn7** [comment]
The best way to elaborate on this is in the form of a PR. I'll get to this ASAP.
