### ISSUE TITLE
Allow additional characters in label names

### ISSUE THREAD

**Issue by cstockton** [prometheus/common#182]
This is in response to the closed issue #180. I would like to understand the consequence of not following the Prometheus label naming? Currently the official Prometheus exporters for every language contain characters outside this list such as slashes. Even the page about valid label names for exporters contains an example using slashes directly underneath https://prometheus.io/docs/concepts/data_model/#notation, which I think confuses users (myself included):

For example the official https://github.com/prometheus/node_exporter uses ".", "-" - both of which I myself use because they are good for representing canonical locations of pkgs and urls. My main concern is down the road having all my metrics break, because I've made a huge commitment to Prometheus and community provided exporters.

It would be catastrophic to the ecosystem if suddenly all the official exporters, middlewares, tooling and such all stopped working. Knowing this, if a guarantee is made that no such breakage will occur, it makes sense to me they are just adopted as allowed to cement this promise.

**Comment by brian-brazil** [comment]
You're confusing label names and label values. Label values is already as big as possible, any valid UTF-8. Label names are limited, and expanding them would cause breakage across the ecosystem.

**Comment by cstockton** [comment]
/facepalm, you're absolutely right and it even says so in the docs, sorry for the noise!

> "Label values may contain any Unicode characters."
