### ISSUE TITLE
TextParser: Allow streaming

### ISSUE THREAD

**Issue by beorn7** [prometheus/common#2]
Recently, we have made the definition of the line-based text format more restrictive. Lines for one metnic family must be continuous, so we can now implement streaming. Change the interface of the parser to a channel spitting out metric families (and provide the old interface for compatibility, noting that it is less efficient).

**Comment by joeblew99** [comment]
Has the streaming been fully incorporated yet ? anyone know.
I am very much into using streaming style as much as possible.

**Comment by beorn7** [comment]
I like to believe this will be an easy change. But it's currently preempted by more important tasks.

Are you running into concrete problems because of the lack of streaming? That would at least make this issue a less academic one.

**Comment by beorn7** [comment]
For high speed ingestion, a more direct approach to parsing the text format will be taken in v2.0 (i.e. not via converting to protobuf as an intermediate format). The existing text parser might still be useful for other use cases, but certainly not for anything high performance. I'm therefore closing this as "won't fix".
