### ISSUE TITLE
Build error concerning mf

### ISSUE THREAD

**Issue by WelverinRaven** [prometheus/common#200]
go vet ./... prints:
`# github.com/prometheus/client_golang/prometheus

../../../../github.com/prometheus/client_golang/prometheus/http.go:88:24: cannot use mf (type *"github.com/prometheus/client_model/go".MetricFamily) as type *"github.com/prometheus/common/vendor/github.com/prometheus/client_model/go".MetricFamily in argument to enc.Encode

../../../../github.com/prometheus/client_golang/prometheus/registry.go:558:41: cannot use mf (type *"github.com/prometheus/client_model/go".MetricFamily) as type *"github.com/prometheus/common/vendor/github.com/prometheus/client_model/go".MetricFamily in argument to expfmt.MetricFamilyToText`

**Comment by brian-brazil** [comment]
Fixed by #199
