### ISSUE TITLE
JSON marshal and unmarshal functions for model.Duration

### ISSUE THREAD

**Issue by sid-agrawal** [prometheus/common#227]
Ran into the following error when I tried Unmarshalling a JSON output of `github.com/prometheus/alertmanager/config.Config.`

```
json: cannot unmarshal string into Go struct field 
alertmanagerConfig.value.route.routes.group_interval of type model.Duration
```

Looks like there are no UnmarshalJSON and MarshalJSON methods for model.Duration. And a simple fix would be to add those methods. I can make PR if folks agree that, that is the right fix.

**Comment by roidelapluie** [comment]
Fixed in https://github.com/prometheus/common/pull/280
