### ISSUE TITLE
expfmt.NewEncoder do not support custom encoder 

### ISSUE THREAD

**Issue by hidu** [prometheus/common#269]
now is
```
switch format{
   case FmtProtoDelim:
  case xxx:
   panic(fmt.Errorf("expfmt.NewEncoder: unknown format %q", format))
}
```

expect:
```
switch format{
   case FmtProtoDelim:
  case xxx:
  default:
   // so we also need RegisiterEncoder(format,enc)
    if enc,ok:=encoders[format];ok{
       return enc
   }
   panic(fmt.Errorf("expfmt.NewEncoder: unknown format %q", format))
}
```

**Comment by roidelapluie** [comment]
This repository is an internal prometheus library.

Formatting metrics can be tricky and I am not willing to have tens of ways to encode/decode metrics.

What is your use case? Which encoder are you willing to add?

Thanks.

**Comment by hidu** [comment]
in my company, we use our own system, but now the prometheus system is not ready.
so in my app,  we expect use prometheus api now，and we can export to our old system.
when prometheus system is ready，then we switch it

**Comment by roidelapluie** [comment]
I am unsure why you would be wiring to Prometheus at a so low level. However if you really want to do so I would recommend to have your temporary internal fork.

If you want more advices from the community I suggest you reach out to the mailing list or our discourse forum: https://prometheus.io/community
