### ISSUE TITLE
Implicit proxy configuration is not supported in http_config

### ISSUE THREAD

**Issue by c16a** [prometheus/common#288]
When a new `http.Client` is being created from `HTTPClientConfig`, only explicit proxy configuration is supported. Implicit proxy configurations such as HTTP_PROXY, HTTPS_PROXY, and NO_PROXY are ignored.

https://github.com/prometheus/common/blob/4240322d2138024beddb57544851d77a08afe19c/config/http_config.go#L220-L240

If there is no proxy URL provided by application, relevant proxies should be picked up from the environment.

**Comment by roidelapluie** [comment]
closing as per https://github.com/prometheus/prometheus/issues/8720#issuecomment-831154231
