### ISSUE TITLE
Snyk reports vulnerability via dependency go-kit

### ISSUE THREAD

**Issue by satr** [prometheus/common#292]
https://app.snyk.io/vuln/SNYK-GOLANG-GOETCDIOETCDV3PKGHTTPUTIL-1083906

Introduced through
github.com/prometheus/common@v0.20.0 and github.com/prometheus/client_golang@v1.10.0
Fixed in
go.etcd.io/etcd@3.4.0

**Comment by roidelapluie** [comment]
Thank you. As prometheus does not use etcd, we are unaffected. It is an unused transient dependency.
