### ISSUE TITLE
Critical vulnerability discovered in GoGo Protobuf before 1.3.2

### ISSUE THREAD

**Issue by krishnakumar4a4** [prometheus/common#315]
One of the internal security vulnerability scan is showing this package has a dependency on GoGo Protobuf library which has vulnerability as mentioned here
https://ossindex.sonatype.org/vulnerability/dcf6da03-f9dd-4a4e-b792-0262de36a0b1

Do you have any plans to upgrade this package github.com/gogo/protobuf@v1.1.1 to v1.3.2 anytime soon? Are there any other points that can possibly impact this update?

P.S: We are planning to use github.com/prometheus/client_golang@v1.11.0 package for exporting metrics in one of the go service which indirectly depends on this package.

**Comment by beorn7** [comment]
This package does not depend on github.com/gogo/protobuf@v1.1.1 anymore.

It did (accidentally) in v0.4.1. With the way Go Modules dependency tracking works, you will see github.com/gogo/protobuf@v1.1.1 in go.sum and in `go mod graph` more or less forever. But its code is not used.

**Comment by kwontae** [comment]
Is there any way for us to avoid this from showing up in go.sum? I think we can use the replace functionality in go.mod possibly. 
This keeps raising the vulnerability issue in our environment.

**Comment by rcousineau-xandr** [comment]
I was running into this as well... there are several closed issues on this repo + some closed issues on the prometheus/client_golang repo too.

Linked to one of them was this pr: https://github.com/wavesplatform/gowaves/pull/678/files

I followed what they did in their project and added `exclude github.com/gogo/protobuf v1.1.1` to my go.mod and that fixed it.
