### ISSUE TITLE
Introduce a version indentifier

### ISSUE THREAD

**Issue by RichiH** [prometheus/common#34]
I know that the export format is not supposed to change any more, but never say never...

`prometheus_metric_version` or even something more generic like `metric_exposure_version` would allow for upgrades, and for queries to see if anything still runs old versions prior to upgrading.

**Comment by brian-brazil** [comment]
Is `prometheus_build_info` what you're looking for?

**Comment by juliusv** [comment]
I think he means the format version of the exposing client. That wouldn't even have to be an explicit metric mentioned in the exposed output - the Prometheus server learns about the version from the Content-Type header. It could then generate a synthetic metric about target metric exposition format versions, similar to `up`. Whether we want that or not is a different question.

**Comment by RichiH** [comment]
Correct, I am talking about the clients. If there ever was a transition, it
would be too late to introduce it to all exporters which are, by then,
legacy.
Having it in the header means breaking changes would be possible, having it
in the text means humans can easily debug it.

Richard

Sent by mobile; excuse my brevity.

**Comment by beorn7** [comment]
I think the header is the right place. We could encourage producers of the text format to put the version as a comment in the first line, but it should not be part of the exchange format itself.

**Comment by RichiH** [comment]
I think I like Björn's idea; a lot, actually.

This also makes the existence of the metric obvious to users who are not
aware of it. The header-only solution would hide it.

Richard

Sent by mobile; excuse my brevity.

**Comment by brian-brazil** [comment]
That only works for the text format, and I'm a bit hesitant to throw in additional metadata in comments.

I think this is something we can look at on the Prometheus side if we're ever making a breaking change in the future.

**Comment by RichiH** [comment]
Text would be for the comment only, the actual information would be in the
header.

Richard

Sent by mobile; excuse my brevity.

**Comment by beorn7** [comment]
I think this is right now more an issue of specification than of implementation. See https://github.com/prometheus/docs/issues/545

I'm closing this to funnel the discussion to the linked issue.
