### ISSUE TITLE
HTTPClientConfig should check if it is nil

### ISSUE THREAD

**Issue by grobinson-grafana** [prometheus/common#354]
I think `HTTPClientConfig` in `config/http_config.go` should check if it is `nil` when calling `func (c *HTTPClientConfig) Validate() error`. It can return either `nil` or an `error`, however I think `nil` is more appropriate since a `nil` `HTTPClientConfig` means there is no configuration.

```
func (c *HTTPClientConfig) Validate() error {
    if c == nil {
        return nil
    }
    ...
}
```

**Comment by roidelapluie** [comment]
Where in the prometheus codebases do we have a nil configuration? This should never happen, because there should at least be a default config. Panicing is the right thing to do here.
