### ISSUE TITLE
`TextToMetricFamilies` fails to parse duplicated HELP and TYPE.

### ISSUE THREAD

**Issue by macunha1** [prometheus/common#355]
I've recently faced an issue with an exporter that is displaying duplicated metrics due to a race condition, it is a bug and was reported to the authors. However, while that is not fixed, our client needs to parse and de-duplicate the entries before calling `TextToMetricFamilies`.

I would like to know whether it would be interesting/make sense to implement something in this repo to be more resilient when it comes to that.

This is the error:

```
text format parsing error in line 123: second HELP line for metric name "..."
```

These comments refer to de-duplication on the metric level https://github.com/prometheus/common/blob/296a433/expfmt/text_parse.go#L82-L91;

How could we make HELP and TYPE more tolerant/resilient as well?
Would it make sense to provide this at `prometheus/common` or should it be indeed handled on the client?

Thanks!

**Comment by macunha1** [comment]
> If you check out the structure of the output type of `TextToMetricFamilies`, i.e. `map[string]*dto.MetricFamily`, you will realize the problem: For each metric name, there is exactly one `dto.MetricFamily`

That is right, however, what surprised me in this scenario was that I had two instances of `dto.MetricFamily` containing the very same name. I would expect the library to raise a failure sooner on the expected-to-be unique `dto.MetricFamily`, not a failure only when parsing the HELP+TYPE comments because they going twice to the first `dto.MetricFamily.name` match.

[warning: keep in mind that I am not fully into the code base, I might be sharing wrong info]

> What's your exact plan to make things more tolerant/resilient?

Something like a names' hash table that we can check for `dto.MetricFamily` instances. That would either:
a. support routing to multiple `dto.MetricFamily` based on the name (misleading and error-prone), or
b. check if the name already exists and fail if it does.

**Comment by beorn7** [comment]
Hmm, not sure I'm following.

`TextToMetricsFamilies` is about parsing the Prometheus text format. It naturally repeats the metric family name on each line with a sample value. However, it is specified such that the HELP and TYPE line must only appear at most once per metric family name.

It appears to me the code is exactly implementing the spec here.
