### ISSUE TITLE
Feature request: add support for client-credentials oauth2 authorization using proxy

### ISSUE THREAD

**Issue by YonathanIntel** [prometheus/common#357]
@roidelapluie  Add support for client-credentials oauth2 authorization using proxy.

**Comment by roidelapluie** [comment]
What do you mean?

**Comment by YonathanIntel** [comment]
I mean that when you set proxy_url for remote-write with  oauth2 it doesn't use the proxy and the oauth2 authorization fails. so I need a way to get the oauth2 use the proxy url and pass my corporate proxy.
