### ISSUE TITLE
Consistently treat a label with an empty value as non-existant

### ISSUE THREAD

**Issue by beorn7** [prometheus/common#36]
Currently, the signature AKA fingerprint of a metric changes if a label with an empty value is added.

**Comment by beorn7** [comment]
Un-assigning from myself as I intend to focus on other Prometheus project. Also, this is something that will change with Prometheus 2.x, where I have little involvement. I leave it to the experts to figure out how to deal with this issue.

**Comment by brian-brazil** [comment]
I've looked through the 2.x code, and we're handling this correctly on ingestion in `mutateSampleLabels`.  Recording rules also look good.

However, alerting rules are not handling this correctly.
