### ISSUE TITLE
Feature Request: Ability to set custom User-Agent on oauth2 

### ISSUE THREAD

**Issue by cig2312** [prometheus/common#384]
Currently the User-Agent on the oauth2 client is `Go-http-client/1.1`. 
This leads to the oauth2 flow being ratelimited on many sites. 

Having the option of setting a custom UA would resolve this issue.

**Comment by roidelapluie** [comment]
Can you please be more specific with the issue you try to solve? I don't think rate limiting on UA is something useful.
