### ISSUE TITLE
Please migrate to new Yaml Version V3

### ISSUE THREAD

**Issue by reachlakstar** [prometheus/common#397]
Twistlock is throwing vulnerability with Yaml V2, can you please migrate to V3

**Comment by roidelapluie** [comment]
There are outstanding issues with Yamlv3. If you have found a vulnerability issue, please see our security model: https://prometheus.io/docs/operating/security/ 

> Special note for security scanner users: Please be mindful with the reports produced. Most scanners are generic and produce lots of false positives. More and more reports are being sent to us, and it takes a significant amount of work to go through all of them and reply with the care you expect. This problem is particularly bad with Go and NPM dependency scanners.

> As a courtesy to us and our time, we would ask you not to submit raw reports. Instead, please submit them with an analysis outlining which specific results are applicable to us and why.

**Comment by reachlakstar** [comment]
@roidelapluie this is an outstanding issue, will cause application fail to move production, could you please look in to the issue

**Comment by roidelapluie** [comment]
I don't think there is a known vulnerability in yaml v2
