### ISSUE TITLE
unmarshalerDecoder Error with string query

### ISSUE THREAD

**Issue by martialblog** [prometheus/common#423]
Hi, 

I was wondering if this is a bug or if I'm just using the library wrong.

When trying to send a String query to the server with the golang client like so:
`result, warnings, err := v1api.Query(ctx, "\"up\"", time.Now(), v1.WithTimeout(5*time.Second))
`

It results in an error:
`
Error querying Prometheus: unmarshalerDecoder: unexpected value type "string", error found in #10 byte of ...|.97,"up"]}|..., bigger context ...|esultType":"string","result":[1670860804.97,"up"]}|...
exit status 1
`

Since server accepts the query when I send it via curl for example, everything seems fine:

```
curl --data-urlencode 'query="up"' localhost:9090/api/v1/query              
{"status":"success","data":{"resultType":"string","result":[1670861105.448,"up"]}}
```

Since the golang client tried to decode the JSON into a v model.Value I opened the issue here. 

I know that the docs say that:
> String - a simple string value; currently unused

but I assumed the library would still be able to parse the response.

Cheers
Markus

**Comment by martialblog** [comment]
Ok, maybe it's really not implemented in the client_golang? https://github.com/prometheus/client_golang/blob/main/api/prometheus/v1/api.go#L590

**Comment by roidelapluie** [comment]
try: `result, warnings, err := v1api.Query(ctx, "up", time.Now(), v1.WithTimeout(5*time.Second))`

**Comment by martialblog** [comment]
Hi, 

with `Query(ctx, "up", time.Now()` I get the actual up metric back, which works as expected. I'm really trying to get the "resultType":"string" back. But I saw that the client_golang Unmarshall doesn't support that yet.

Thanks
