### ISSUE TITLE
Expose SSL keys during debug

### ISSUE THREAD

**Issue by luizluca** [prometheus/common#441]
Hello,

It would be nice to have a way to decrypt https traffic. I'm trying to reproduce a blackbox http access that is failing only with prometheus blackbox. It would be nice to have the SSL keys exposed for debug. Maybe it would use the classic SSLKEYLOGFILE env var, a tls_config setting, or even expose the required attributes as properties.

For reference: https://www.benburwell.com/posts/intercepting-golang-tls-with-wireshark/

**Comment by roidelapluie** [comment]
Exposing SSL keys for debugging purposes is not recommended due to the significant security risks involved. Therefore, it is unlikely to be accepted upstream in the Prometheus ecosystem. However, you could still compile the blackbox exporter with this flag enabled on your own.
