### ISSUE TITLE
Internally vendor all packages that are not exposed in any types exported by prometheus/common

### ISSUE THREAD

**Issue by aanm** [prometheus/common#45]
I can't build my project which I believe is because of this...

godep version `godep v71 (linux/amd64/go1.6)` doesn't seems to import the `github.com/prometheus/common/internal/bitbucket.org/ww/goautoneg` directory to vendor so I got a:

```bash
$ go install ./...
....
  imports github.com/prometheus/common/expfmt
  imports github.com/prometheus/common/internal/bitbucket.org/ww/goautoneg: use of internal package not allowed
```

Linking to godep issue https://github.com/tools/godep/issues/490

**Comment by mkumatag** [comment]
I also faced this issue while building k8s.io/heapster project with updated github.com/boltdb/bolt, any update on this issue?

**Comment by beorn7** [comment]
If I understood @fabxc correctly, we will finally go for internal vendoring of all types that are not exposed by any exported types within this repo.
I'll adjust the title of this issue accordingly.

**Comment by beorn7** [comment]
After all, we decided to not go for internal vendoring for the time being.
