### ISSUE TITLE
common v0.43.0 is not supporting kube-state-metrics v2.8.2 prometheus metrics format

### ISSUE THREAD

**Issue by ukumar009** [prometheus/common#488]
I am seeing below parsing errors
```
text format parsing error in line 4: second HELP line for metric name "kube_customresource_csv_status" 
text format parsing error in line 1488: unknown metric type "info" 
```

expfmt.TextParser{} is not able to parse metrics with below type:

kube_customresource_csv_status
kube_customresource_abc_info

**Comment by beorn7** [comment]
`expfmt.TextParser` is a parser for the classical Prometheus text format. The `info` typ doesn't exist in that format. It has been introduced by OpenMetrics, and there is currently no OpenMetrics parser implemented in the prometheus/common repository. (There is one included in prometheus/prometheus, see https://github.com/prometheus/prometheus/blob/main/model/textparse/openmetricsparse.go .)

However, a second HELP line for the same metric name is invalid in both the classical Prometheus text format as well as OpenMetrics.

**Comment by ukumar009** [comment]
Thank you @beorn7 I will look into https://github.com/prometheus/prometheus/blob/main/model/textparse/openmetricsparse.go
