### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by YannickTeKulve** [prometheus/common#526]
Hi

Not entirely sure if this is the correct place to ask.

The latest is from may. But meanwhile some features are added (like https://github.com/prometheus/common/pull/511 ) and other minor updates. It would be be nice if this was released and used in prometheus and actually can be used.

Thx for everything!

**Comment by SuperQ** [comment]
Yes, it took a while to get the client_golang changes done to cut a new release. I think we're ready for this now.

**Comment by SuperQ** [comment]
Done: https://github.com/prometheus/common/releases/tag/v0.45.0

**Comment by YannickTeKulve** [comment]
@SuperQ Thx!
