### ISSUE TITLE
Update expfmt/text_parse.go to support the new UTF-8 syntax

### ISSUE THREAD

**Issue by ywwg** [prometheus/common#554]
text_parse is a go implementation of a parser for the plain prometheus text format

**Comment by jmichalek132** [comment]
I spoke with @ywwg and I would be willing to help with this one over the holidays, could I get this one assigned to me please?

**Comment by jmichalek132** [comment]
Notes from the chat:

the basic changes are:
* current code assumes there must be a metric name before "{". Now, it is ok if a line begins with "{"
* currently, terms inside {} must have an operator, like = or =~. Now, if there is a quoted term without an operator, that is the * metric name. There can only be one term without an operator.
* the left hand side of operators inside {} can be quoted
* for HELP and TYPE and UNIT lines, the metric name may be in quotes.
* best way to attack this is probably creating the test cases and then fixing the code so they all pass

**Comment by bwplotka** [comment]
👍🏽  Thanks!

**Comment by ywwg** [comment]
@jmichalek132 checking in, any progress on this?

**Comment by jmichalek132** [comment]
> @jmichalek132 checking in, any progress on this?

sorry unfortunately not I was sick over the holidays, but I'll take a stab at this over the weekend.

**Comment by jmichalek132** [comment]
So finally looking into this today, first thing I am unclear on based on the proposal is what should be the behaviour with the metric name in the prometheus metadata.
I assume if the metric name is valid it should keep working as is.
If it has utf-8 characters it has to be quoted around in the metadata.
Is this assumption correct @ywwg ?

**Comment by jmichalek132** [comment]
Also when the metric name is surrounded by the double quote I assume we need to validate that if the metric name contains double qoute it's properly escaped right? Otherwise the parsing could break.

**Comment by ywwg** [comment]
In the other parsers, I changed them so they can just read the new format without a flag. It was not practical to create switching logic without duplicating all the parsers. Let's start by not using a flag.

> I assume if the metric name is valid it should keep working as is.
> If it has utf-8 characters it has to be quoted around in the metadata.

Yes that's correct.

The current parser supports escaping already, so it should be fine to use that escaping inside double quotes for the TYPE and HELP lines:

```
# HELP "my.\"noncompliant\".metric" help text
# TYPE "my.\"noncompliant\".metric" counter
```

**Comment by ywwg** [comment]
Checking in on this again, is there a PR attached?

**Comment by jmichalek132** [comment]
Sorry for the delays I didn't have a chance to make much progress on this, if it's delays are an issue, please do re-assign it to someone else. Otherwise I should be able get time to work on it / publish draft next weekend.

**Comment by ywwg** [comment]
Thanks for letting me know! yeah I think we need to move ahead on this more quickly so I'll be reassigning it. I appreciate your contribution regardless

**Comment by ywwg** [comment]
@fedetorres93

**Comment by fedetorres93** [comment]
I'll take this issue :+1:

**Comment by ywwg** [comment]
done!
