### ISSUE TITLE
TextParser: parsing timestamps for summaries and histograms

### ISSUE THREAD

**Issue by deadtrickster** [prometheus/common#59]
Hey!

It looks like: https://github.com/prometheus/common/blob/master/expfmt/text_parse.go#L448 
there is no validation that for histograms or summaries timestamps are the same across buckets. quantiles, count and sum. Basically last specified timestamp wins.

**Comment by beorn7** [comment]
Which might be the right thing to do.
This is first and foremost a specification issues. I have filed https://github.com/prometheus/docs/issues/552 for that.

Closing this for now. Once the specification is clear about it, a new issue will be filed here if needed.
