### ISSUE TITLE
Support for configuring ciphersuites in tls_config

### ISSUE THREAD

**Issue by garyclee** [prometheus/common#626]
Hi @roidelapluie 

I have a need to configure cipher suites on the scrape interface. Would you be open to a contribution to add 'cipher_suites' to 'tls_config' (https://prometheus.io/docs/prometheus/latest/configuration/configuration/#tls_config)? I note that TLS 1.3 ciphersuites are not configurable in Go.

Such a configuration exists on the server side (https://prometheus.io/docs/prometheus/latest/configuration/https/).

Thanks!

**Comment by veso0308** [comment]
Do you have an update on this?
Since blackbox 0.26 and crypto/tls 0.32 my needed cipher suites are not listed anymore under "secure" and therefor not valid anymore.
Would be great to match the config which is used on the server side.
