### ISSUE TITLE
Consider defaulting model.NameEscapingScheme to model.UnderscoreEscaping

### ISSUE THREAD

**Issue by dashpole** [prometheus/common#689]
Forked from https://github.com/open-telemetry/opentelemetry-go/pull/5755#issuecomment-2327427065

When trying utf-8 support with OpenTelemetry, I found the default `model.NameEscapingScheme` of `model.ValueEncodingEscaping` surprising.  It converted my metric name to `U__rpc_2e_durations_2e_histogram_2e_seconds`.

Underscore escaping is the most human-readable of the escaping schemes. For anyone using a system that doesn't support the new UTF-8 stuff, or even curl, being able to read the output or find/read the names when querying is probably more important.  I also suspect, but haven't verified, that most existing escaping schemes replace with underscores (at least OpenCensus/OpenTelemetry currently do).  If we defaulted to underscore replacement, it would make the migration easier on that front.

@ywwg

**Comment by ywwg** [comment]
I am ok with this approach. The main reason to escape to ValuesEncoding is to preserve round-tripability of the escaped names. Once we convert to underscores, that possibility is lost. However simple underscore replacement has been the chosen approach for Prometheus for a long time, so it's probably better to keep things familiar.  I'll prepare a PR.
