### ISSUE TITLE
Info and color codes logged to stdout

### ISSUE THREAD

**Issue by discordianfish** [prometheus/common#71]
_From @jsha on September 4, 2016 22:19_

Steps to reproduce:

```
node_exporter --log.format 'logger:syslog?appname=node_exporter&local=7' &
less /var/log/syslog
```

Expected result: node_exporter log lines don't contain spelled-out severities or ANSI color codes.

Actual result: node_exporter log lines do contain severities and color codes.

```
Sep  4 22:16:31 btudb node_exporter[15767]: @cee:#033[34mINFO#033[0m[0000] Starting node_exporter (version=0.12.0, branch=master, revision=df8dcd2)  #033[34msource#033[0m=node_exporter.go:135
Sep  4 22:16:31 btudb node_exporter[15767]: @cee:#033[34mINFO#033[0m[0000] Build context (go=go1.6.2, user=root@ff68505a5469, date=20160505-22:14:18)  #033[34msource#033[0m=node_exporter.go:136
Sep  4 22:16:31 btudb node_exporter[15767]: @cee:#033[34mINFO#033[0m[0000] No directory specified, see --collector.textfile.directory  #033[34msource#033[0m=textfile.go:57
```

_Copied from original issue: prometheus/node_exporter#298_

**Comment by discordianfish** [comment]
_From @SuperQ on September 5, 2016 7:37_

Yikes, I guess that's coming from the logging library.  May be an issue for all use of our common logging[0](https://github.com/prometheus/common/blob/master/log).

**Comment by brian-brazil** [comment]
This relates to the old log library (we use promlog now), which is deprecated and no longer in use.
