### ISSUE TITLE
Logrus case change

### ISSUE THREAD

**Issue by lupoDharkael** [prometheus/common#78]
the log package imports `"github.com/Sirupsen/logrus"` but it should be `"github.com/sirupsen/logrus"` [check it here](https://github.com/sirupsen/logrus/issues/451). This is painful because I use Logrus in my project and I don't want to have the same library in different folders with different names.

**Comment by grobie** [comment]
The change was ultimately reverted as noted in their README and in this issue:

> If we wish to provide a lower-case name-change, we'll do so under a different name.

You should use `Sirupsen/logrus` instead.
