### ISSUE TITLE
Syslog and eventlog "formatters" are wrong

### ISSUE THREAD

**Issue by fabxc** [prometheus/common#82]
Both are hooking into logrus' formatting mechanism. This is meant to create a byte slice, which logrus then writes to a sink. Instead both formatters write to their own sync as a side effect. The formatted log lines proceed being printed into the original sink, i.e. stdout.

The side effect is obviously bad as there's stuff logrus does internally afterwards.
But it's also just inconsistent from the configuration side. We pretend the flag flips the sink, when in fact it just adds one that as written to in a non-intended way.

The configuration aspect is possibly too far along to fix.

**Comment by amankapoor** [comment]
Hi, the thing which you have mentioned is true, everything is going to stdout. I faced the same problem today. I wanted to write to a file, so I solved it for my purpose. I added a SetOutput function and removed l.Out = w from NewLogger function. You might want to look into it - https://github.com/amankapoor/prometheus-common-log-to-file/.

**Comment by brian-brazil** [comment]
This relates to the old log library (we use promlog now), which is deprecated and no longer in use.
